name: gligen_demo
channels:
  - xformers/label/dev
  - pytorch
  - defaults
dependencies:
  - python=3.10.8
  - pip=22.2.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - xformers
  - pip:
    - omegaconf==2.1.1
    - albumentations==1.3.0
    - opencv-python
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - test-tube>=0.7.5
    - streamlit==1.12.1
    - einops==0.3.0
    - git+https://github.com/openai/CLIP.git
    - protobuf~=3.20.1
    - torchmetrics==0.6.0
    - transformers==4.19.2
    - kornia==0.6.0
    - gradio==3.16.0